backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

  backend:
  name: git-gateway

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
