backend:
  name: git-gateway


media_folder: "src/images" # Folder where user uploaded files should go
public_folder: "images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      -file: content/_index.md
      label: "Home Page"
      name: "home"
      fields:
      - {label: Title, name: title, widget: string}
